### ISSUE TITLE
Tunnelling with MiraWeb + localtunnel

### ISSUE THREAD

**Issue by delucis** [Cycling74/xebra.js#32]
Is there any more information available or a working example of tunnelling (e.g. with `localtunnel`) to enable devices not on the same network to talk to Max?

I can use `localtunnel` to access HTML files no problem — as described in[`examples/07-tunneling/README.md`](https://github.com/Cycling74/xebra.js/blob/dev/examples/07-tunneling/README.md) — but the WebSocket connection fails. I’ve tried it with simple xebra sketches (using `http-server`) as well as with the default MiraWeb `mira.frame` display page (using the server Max runs), but no luck.

Thanks!

**Comment by catarak** [comment]
Hey @delucis--I'll take a look at this. Are you saying that MiraWeb doesn't work for you at all?

**Comment by delucis** [comment]
Hi @catarak — thanks!
No, it mostly works super well. I can run it between Max & a browser on the same local network, but was trying to figure out a way to open that up to browsers not on the same network. `localtunnel` serves the HTML/CSS/JS assets successfully, but I couldn’t get the WebSocket connection to work (which means no MiraWeb interface other than the connection modal).

**Comment by catarak** [comment]
I think the issue is that the website is running on a different port from the websocket connection. The solution I've found is to 

1. Open a tunnel for the port your website is running at, i.e. `lt -p 8080 -s xebra`
2. Open another tunnel for the port that a `mira.frame` is listening, i.e. `lt -p 8086 -s miraframe`
3. Go to http(s)://xebra.localtunnel.me
4. In the connection dialogue, put `miraframe.localtunnel.me` for the host and `80` for the port.

**Comment by delucis** [comment]
Amazing! Just confirmed this works.

I think actually the main missing piece of information in [the example documentation](https://github.com/Cycling74/xebra.js/blob/dev/examples/07-tunneling/README.md) is the bit about port `80` for the WebSocket connection. If it’s helpful, now that I’ve figured it out, I’d be happy to submit a pull request to tweak that example.

**Comment by catarak** [comment]
yes, go ahead and submit a PR!

**Comment by delucis** [comment]
OK, working on it! Should I fork `master` or `dev`?

**Comment by fde31** [comment]
hey @delucis we actually made a big change yesterday by moving to a Monorepo approach for xebra.js and MiraWeb. For this I'd ask you to fork and make the PR on this repo https://github.com/Cycling74/miraweb . you can find the former xebra.js code in `packages/xebra.js`. For now I'd also say stick to the `dev` branch. Thx for helping!
